Add Linux for PHP ElePHPant
f500/elewant pull request #245
Opened 2019-09-26 22:43 UTC by IgorSantos17

2019-09-26 23:35 UTC, cookieguru requested changes

2019-09-26 23:35 UTC, cookieguru commented on src/Elewant/Herding/DomainModel/Breed/Breed.php
> +    public const BLUE_PHPCE_REGULAR = 'BLUE_PHPCE_REGULAR';
See #213

2019-09-26 23:36 UTC, cookieguru commented
The PHPCon Poland is also not officially-licensed

2019-09-27 12:31 UTC, IgorSantos17 commented
are add only the officers?
I think a lot of people have and are interested in these others

2019-09-27 13:31 UTC, ramondelafuente commented
Yes. Because we feel it's not fair to encourage unofficial elephpants.

2019-09-27 14:35 UTC, closed without merging

2019-09-27 14:36 UTC, IgorSantos17 commented
Ok, understand.
I closed PR.
Is linux for php ElePHPant is official?

2019-09-27 15:42 UTC, cookieguru commented
I would say so, they thanked Vincent in [the announcement tweet](https://twitter.com/linuxforphp/status/1156635964363694080)